# Generated by Django 4.0.2 on 2022-02-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_id', models.PositiveIntegerField(verbose_name='Input ID')),
                ('name', models.CharField(max_length=55, verbose_name='Name')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('national_code', models.CharField(max_length=10, verbose_name='National Code')),
                ('total_toll_paid', models.PositiveIntegerField(verbose_name='Total Toll Paid')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'db_table': 'owner',
            },
        ),
    ]
