# Generated by Django 4.0.2 on 2022-02-24 21:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_nodes', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'AllNode',
                'verbose_name_plural': 'AllNodes',
                'db_table': 'all_nodes',
            },
        ),
    ]
