# Generated by Django 4.0.2 on 2022-02-24 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0002_remove_owner_input_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_id', models.PositiveIntegerField(verbose_name='Input ID')),
                ('color', models.CharField(max_length=55, verbose_name='Color')),
                ('length', models.FloatField(verbose_name='Length')),
                ('type', models.CharField(choices=[('S', 'Small'), ('B', 'Big')], max_length=1, verbose_name='type')),
                ('load_valume', models.FloatField(blank=True, null=True, verbose_name='Load Valume')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='owner.owner')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicle',
            },
        ),
    ]
