# Generated by Django 4.0.2 on 2022-02-24 20:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=65, null=True)),
                ('width', models.FloatField(verbose_name='Width')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326, verbose_name='Geometry')),
            ],
            options={
                'verbose_name': 'Road',
                'verbose_name_plural': 'Roads',
                'db_table': 'road',
            },
        ),
    ]
